### ISSUE TITLE
Show Caption on Same Line as StarRating

### ISSUE THREAD

**Issue by ziruixiao** [cameronjroe/react-star-rating#19]
In the examples shown on this site (http://cameronjroe.com/react-star-rating/), all of the StarRating components have their caption shown on the same line/row. However, when I try to implement this, my caption is always on a different row from my star rating, regardless of the display size. Am I doing this right? Thanks!

```
<StarRating name="userRating" size={15} caption="5 votes" disabled rating={3} totalStars={5} />
```

**Comment by ninjasort** [comment]
Looks right. Have you included the CSS?

**Comment by ziruixiao** [comment]
Ah, I believe that was it. Thanks!
