### ISSUE TITLE
move react-addons-test-utils to dev dependencies

### ISSUE THREAD

**Issue by jonathanong** [cameronjroe/react-star-rating#26]
shouldn't be necessary as a depedency

**Comment by jonathanong** [comment]
also all the react dependencies because it makes it harder to upgrade react versions. should use a wider range

**Comment by jonathanong** [comment]
@cameronroe can u fix this quickly or add someone as a collab? this is blocking everyone from updating to react 15

**Comment by ninjasort** [comment]
Hey @jonathanong, sorry about that. I'll look at it tonight.

**Comment by ninjasort** [comment]
Hey man, really sorry but I don't have time to fix this right now. I'll try to get to it as soon as I can, but there's a lot that's going to change with it. Could you just fork it for now?

**Comment by jonathanong** [comment]
just give this guy access https://github.com/cameronroe/react-star-rating/pull/27

**Comment by ninjasort** [comment]
That's potentially a breaking change and will need to switch up the API being used. You're welcome to fork it and give it a go.

**Comment by jonathanong** [comment]
give me access then. i don't have time to maintain a fork. i promise not to make breaking changes :)

**Comment by ninjasort** [comment]
dude, honestly feel free to take the repo. I suck at life.

**Comment by jonathanong** [comment]
published this as https://www.npmjs.com/package/@jongleberry/react-star-rating

**Comment by jonathanong** [comment]
oh my god i'm a contributor. i didn't even know. pushing it here! haha

**Comment by jonathanong** [comment]
@cameronroe can you add me to the npm repo? `npm owner add jongleberry react-star-rating`. thanks!

**Comment by ninjasort** [comment]
So I didn't say you could take the package.

**Comment by jonathanong** [comment]
https://github.com/cameronroe/react-star-rating/commit/35d24f57ffbb3d14d6b587800af7fc6fd622a1bc
