### ISSUE TITLE
react 15 compatibility

### ISSUE THREAD

**Issue by benjipott** [cameronjroe/react-star-rating#28]
Use react 15 compatibility in package?

**Comment by jonathanong** [comment]
i've published this as https://www.npmjs.com/package/@jongleberry/react-star-rating if you'd like to use it. let me know if you'd like to contribute

**Comment by jonathanong** [comment]
https://github.com/cameronroe/react-star-rating/commit/35d24f57ffbb3d14d6b587800af7fc6fd622a1bc

**Comment by benjipott** [comment]
i use it with npm so can you make a tag ?
you could use :
"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-0"
}
