### ISSUE TITLE
Update rating

### ISSUE THREAD

**Issue by InDate** [cameronjroe/react-star-rating#3]
Trying to update the rating through React props programatically vs the onclick but the component is not updating. Any tips? 

```
            <StarRating
              name="react-star-rating"
              rating = { this.props.rating }
              step= { 1 }
              ratingAmount= { 10 }
              onRatingClick = { this.onRatingClick.bind(this) } />
```

**Comment by ninjasort** [comment]
Thanks for the issue. Upgrade to [v1.3.0](https://github.com/cameronjroe/react-star-rating/releases/tag/v1.3.0)

**Comment by InDate** [comment]
Hey mate, thank you. 

Any chance you can push it to NPM?

**Comment by ninjasort** [comment]
Yeah, just did. Cheers!
