### ISSUE TITLE
Old versions of react.

### ISSUE THREAD

**Issue by kojuka** [cameronjroe/react-star-rating#34]
Are you sure you published the latest version to npm?
When I do:
`npm install react-star-rating@1.4.2 --save`
I get the following: 
`└─┬ react-star-rating@1.4.2
  ├─┬ react@0.14.8
  │ ├─┬ envify@3.4.0
  │ │ └─┬ jstransform@10.1.0
  │ │   ├── base62@0.1.1
  │ │   ├── esprima-fb@13001.1001.0-dev-harmony-fb
  │ │   └── source-map@0.1.31
  │ └─┬ fbjs@0.6.1
  │   ├── core-js@1.2.6
  │   └── whatwg-fetch@0.9.0
  ├── react-addons-test-utils@0.14.8
  └── react-dom@0.14.8`

Notice the old versions of react, react-addons-test-utils, and react-dom.  Having two versions of react in my code was causing issues.

But when I do:

`npm install git+https://git@github.com/cameronroe/react-star-rating.git --save`

I get the corrected versions of react, react-dom, etc. 
Anyone else seeing the same thing?

**Comment by Martindelataille** [comment]
same problem.

Fixed with:
`npm i @jongleberry/react-star-rating --save-dev`

**Comment by sohkai** [comment]
@cameronroe @jonathanong If either of you have a few spare minutes, would you mind releasing a new version (that would also include #27)?

**Comment by jonathanong** [comment]
sorry i don't have access to this module. i'm probably going to remake it though because this module has issues with mouse hovers

**Comment by dkumor** [comment]
was this fixed? I noticed this issue was closed - but the NPM nodule was not updated.
