### ISSUE TITLE
This doesn't work with Angular

### ISSUE THREAD

**Issue by stephenhandley** [cameronjroe/react-star-rating#37]
I tried using this with Angular but it doesn't work as advertised. Please advise.

**Comment by ctrlaltdylan** [comment]
I think you might be a little lost

**Comment by stephenhandley** [comment]
@ctrlaltdylan I've literally tried everything but I can't get the star rating widget to show up in my Angular application. I really need a way to do rating in there, and so hopefully you can help

**Comment by ctrlaltdylan** [comment]
I don't see any mention of Angular support for this React component. You need to find an Angular equivalent or make your own. Good luck.

**Comment by stephenhandley** [comment]
thank you for your help @ctrlaltrightdylan you are truly an expert
